---
title: "Schedule"
slug: schedule
output:
  blogdown::html_page:
    keep_md: true # do this to save results in .md file
---

Here’s your roadmap for the semester! *Note:* this will inevitably change throughout the semester as we develop the course together. Please visit this page regularly throughout the semester.

### Overview

The class is structured with three distinct bits. First, the Tuesday lecture will give an overview of the topic for the week. Next, the Thursday lecture will have a short, practical lecture and an activity which is designed to give you hands-on experience and a greater understanding of the broader material. Finally, you will complete weekly writings (short) and labs (also short; requiring coding in `R`). Out of class, you will complete readings and complete assignments.

- [**Content**](/content/) (<i class="fas fa-book-reader"></i>): This page contains the readings for the topic. These pages should be read completely. Lectures are *not* an exact replication of the written content; on the contrary, the lectures are intended to keep you focused on the high-level ideas, while the readings are broader and more comprehensive. Accordingly, lectures are shorter than the (often quite lengthy) written content.

- [**Examples**](/example/) (<i class="fas fa-laptop-code"></i>): This page the material that we will discuss in Thursday classes. In addition to teaching specific content, there are many more `R` code examples. These are intended as a useful reference to various functions that you will need when working on (nearly) weekly labs and your group project.

- [**Assignments**](/assignment/) (<i class="fas fa-pencil-ruler"></i>): This page contains the instructions for the weekly lab (1–3 brief tasks) and for the two mini projects + final project. **Labs are due by 11:59 PM (Eastern) on the Monday after they're posted.**

### Office hours reminder:

I highly encourage you to utilize Professor and TA office hours, especially if you have trouble with basic `R` programming. We will hold office hours at the following times:

- Mondays  2pm - 4pm: TA Hui Zhou at [cornell.zoom.us/j/4786955504](https://cornell.zoom.us/j/4786955504?pwd=VitTc1hVSjJSVXovWGJlRG9VQm5TZz09)
- Tuesdays 11am - 12pm: Prof. Gerarden using [the class zoom link](https://cornell.zoom.us/j/98464434953?pwd=VDJuR0RhckttSTBJVVBqUXhDT3FxUT09)
- Other times by appointment: Prof. Gerarden, at [aem2850.youcanbook.me](https://aem2850.youcanbook.me)

You can also reach us by email. The best approach is to email both of us at the same time. You can do that with one click [here](mailto:gerarden@cornell.edu,hz423@cornell.edu).



:::note
**tl;dr**: You should follow this general process (in order) each week:

- Do everything on the content page before Tuesday (<i class="fas fa-book-reader"></i>)
- Come to lecture on Tuesday
- In class on Thursday, we will work through the example page (<i class="fas fa-laptop-code"></i>)
- Complete the lab (<i class="fas fa-pencil-ruler"></i>) and the weekly writing (assigned in class) before the next Tuesday's class.
- As needed, attend the lab hours hosted by the TA.
:::

---

{{< schedule >}}

