---
  class: inverse, center, middle
name: group-project

# Group project

---

  # Overall feedback

  Good job!

  Overall we were pleased with everyone's work

This assignment was meant to push you, and it was interesting to see the approaches different groups took

---

# Group project highlights

Many groups included things like executive summaries, a table of contents, etc. to tie the report together

One group went above and beyond by providing a secondary visualization that they thought improved on the one we had asked for

AEM 5850 groups produced clear slide decks with key results
- Groups rose to the challenge of using our old tools to output something new
- One group added some real polish in post-processing
- Fun fact: quarto can use powerpoint templates

---

# Grading

Median grade was 90%

We posted scores along with feedback on canvas

Please email me, Victor, and Xiaorui if you have any questions about grading
- Do this in a single email so we all have access to the same information

Questions?

